# Generated by Django 5.2.1 on 2025-05-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_payment_id_order_payment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Mailing',
        ),
        migrations.AlterModelOptions(
            name='userquestion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Вопрос пользователя', 'verbose_name_plural': 'Вопросы пользователей'},
        ),
        migrations.AddIndex(
            model_name='userquestion',
            index=models.Index(fields=['is_answered'], name='question_answered_idx'),
        ),
        migrations.AddIndex(
            model_name='userquestion',
            index=models.Index(fields=['user_id'], name='question_user_idx'),
        ),
    ]
